from Classification import NaiveBayes

information_no = {
    "link" : "http://fakenewsarticle.com/a-bunch-of-stuff",
    "website" : "Lorem Ipsum",
    "headline" : "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin sollicitudin, nibh quis viverra ultrices, felis quam porttitor dui, nec posuere tortor enim sit amet lacus. Morbi placerat turpis at volutpat vestibulum.",
    "author" : "John Doe",
    "body" : "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc auctor sollicitudin mi, quis varius nisi semper in. Duis vel lorem dui. In facilisis quam et leo lobortis, non eleifend urna malesuada. Sed efficitur dapibus eros. In fringilla vitae ipsum at auctor. Nunc placerat lorem mauris, eu tincidunt tellus cursus vitae. In eget nunc nunc. Sed sit amet faucibus sapien. Sed tristique mi quis diam viverra, ac suscipit mi rhoncus. Phasellus at lectus eu risus sodales posuere eget et purus. Donec nunc neque, vulputate eget interdum sed, tincidunt eu libero. Fusce et laoreet ipsum. Nulla pulvinar, mi sit amet ullamcorper molestie, ligula arcu facilisis enim, eget viverra neque dolor in magna. Ut id viverra velit, quis blandit ipsum. Etiam quis quam magna. Sed at est felis. Proin vestibulum, risus id luctus aliquam, mi quam tempor eros, sit amet venenatis turpis magna sed nisl. Duis tristique nunc orci, placerat gravida massa commodo in. Phasellus congue interdum turpis et venenatis. Suspendisse lacus est, suscipit sit amet egestas a, ultricies at massa. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Quisque eu accumsan ipsum, vel vehicula magna. Quisque sagittis, nunc et luctus faucibus, sapien nunc laoreet neque, cursus ornare urna quam at est. Vestibulum blandit lacus ac consequat finibus. Donec ut diam velit. Nulla elementum metus id euismod lobortis. Proin finibus libero quam, non ultrices nibh viverra ut. Nullam ac accumsan nibh, vitae feugiat eros. Phasellus vestibulum diam eu metus mattis placerat. Vivamus condimentum tellus orci, nec eleifend est faucibus eu. Nunc semper neque in lectus facilisis efficitur. Donec mattis bibendum tempor. Integer vel felis id quam ultricies convallis ut ut nibh. Aenean rutrum odio ac ante vehicula, et eleifend elit suscipit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed nec orci volutpat, maximus mauris quis, aliquam mauris. Duis sollicitudin ultrices consequat. Donec consectetur justo a quam maximus tempus nec a sem. Etiam lacinia ac massa sed gravida. Nulla nec euismod quam, at accumsan mi. Aenean volutpat semper dolor sit amet dignissim. Phasellus bibendum enim eget nunc vulputate aliquam in in lectus. Vestibulum viverra arcu vitae purus elementum accumsan. Sed scelerisque scelerisque purus ac porta. Nulla elementum elementum tellus, sit amet pretium diam mollis nec. Cras lectus quam, gravida eget congue vel, porta nec neque. Nullam fermentum, erat vitae interdum aliquet, nisl lacus mollis eros, in consequat lectus ante vitae nibh. Fusce ut dignissim enim. In ac lorem tellus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Praesent lacus mauris, placerat quis placerat non, hendrerit tincidunt eros. Quisque lobortis pulvinar fermentum.",
    "pub_date" : "0001-01-01"
}

information_yes = {
    "link" : "http://fakenewsarticle.com/a-bunch-of-stuff",
    "website" : "Lorem Ipsum",
    "headline" : "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin sollicitudin, nibh quis viverra ultrices, felis quam porttitor dui, nec posuere tortor enim sit amet lacus. Morbi placerat turpis at volutpat vestibulum.",
    "author" : "John Doe",
    "body" : "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc auctor sollicitudin mi, quis varius nisi semper in. Duis vel lorem dui. In facilisis quam et leo lobortis, non eleifend urna malesuada. Sed efficitur dapibus eros. In fringilla vitae ipsum at auctor. Nunc placerat lorem mauris, eu tincidunt tellus cursus vitae. In eget nunc nunc. Sed sit amet faucibus sapien. Sed tristique mi quis diam viverra, ac suscipit mi rhoncus. Phasellus at lectus eu risus sodales posuere eget et purus. Donec nunc neque, vulputate eget interdum sed, tincidunt eu libero. Fusce et laoreet ipsum. Nulla pulvinar, mi sit amet ullamcorper molestie, ligula arcu facilisis enim, eget viverra neque dolor in magna. Ut id viverra velit, quis blandit ipsum. Etiam quis quam magna. Sed at est felis. Proin vestibulum, risus id luctus aliquam, mi quam tempor eros, sit amet venenatis turpis magna sed nisl. Duis tristique nunc orci, placerat gravida massa commodo in. Phasellus congue interdum turpis et venenatis. Suspendisse lacus est, suscipit sit amet egestas a, ultricies at massa. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Quisque eu accumsan ipsum, vel vehicula magna. Quisque sagittis, nunc et luctus faucibus, sapien nunc laoreet neque, cursus ornare urna quam at est. Vestibulum blandit lacus ac consequat finibus. Donec ut diam velit. Nulla elementum metus id euismod lobortis. Proin finibus libero quam, non ultrices nibh viverra ut. Nullam ac accumsan nibh, vitae feugiat eros. Phasellus vestibulum diam eu metus mattis placerat. Vivamus condimentum tellus orci, nec eleifend est faucibus eu. Nunc semper neque in lectus facilisis efficitur. Donec mattis bibendum tempor. Integer vel felis id quam ultricies convallis ut ut nibh. Aenean rutrum odio ac ante vehicula, et eleifend elit suscipit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed nec orci volutpat, maximus mauris quis, aliquam mauris. Duis sollicitudin ultrices consequat. Donec consectetur justo a quam maximus tempus nec a sem. Etiam lacinia ac massa sed gravida. Nulla nec euismod quam, at accumsan mi. Aenean volutpat semper dolor sit amet dignissim. Phasellus bibendum enim eget nunc vulputate aliquam in in lectus. Vestibulum viverra arcu vitae purus elementum accumsan. Sed scelerisque scelerisque purus ac porta. Nulla elementum elementum tellus, sit amet pretium diam mollis nec. Cras lectus quam, gravida eget congue vel, porta nec neque. Nullam fermentum, erat vitae interdum aliquet, nisl lacus mollis eros, in consequat lectus ante vitae nibh. Fusce ut dignissim enim. In ac lorem tellus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Praesent lacus mauris, placerat quis placerat non, hendrerit tincidunt eros. Quisque lobortis pulvinar fermentum.",
    "pub_date" : "0001-01-01"
}
nb = NaiveBayes()

result = nb.classify(information_no)

print(result)